<span id="billing-address"></span>

<script type="text/javascript">
  require([
    'jquery',
    'mage/url',
    'Magento_Checkout/js/model/quote',
    'Magento_Customer/js/customer-data',
    'domReady!'], function ($,url,quote, customerData) {
    $('fieldset[data-form="billing-new-address"]').trigger('reset');
    setTimeout(() => window.getBillingAddress('#billing-address'), 200);
    $(document).on('click', '.action-update', function () {
      var fields = $('fieldset[data-form="billing-new-address"]').serialize();
      updateBillingAddress(fields)
    });

    $(document).on('change', "fieldset[class='fieldset'] select[name='town']", function () {
      $(document).find('input[name="city"]').empty().trigger('keyup').val('not-required').attr('aria-required', false).attr('aria-required', false);
      $(document).find('div[name="billingAddresscheckmo.city"]').hide();
      quote.shippingAddress().city = 'not-required';
      setTimeout(() => window.getSuburbs($('fieldset[class="fieldset"] select[name="suburb"]') ,$(this).val()), 200);
    });

    $('input[type=checkbox][name=billing-address-same-as-shipping]').change(function() {
      if(this.checked) {
        window.getCustomAttribute('shipping_address', true, 'billing_address', '#billing-address');
        var address = quote.shippingAddress();
        var queryStrings = $.param(JSON.parse(JSON.stringify(address)));
        updateBillingAddress(queryStrings)
      }
      $("fieldset[class='fieldset'] select[name='town']").trigger('change');
    });

    function updateBillingAddress(fields){
      $.ajax({
        url: url.build('rest/V1/update-billing-address?'+fields),
        type: "POST",
        contentType: "application/json",
        success : setTimeout(() => window.getBillingAddress('#billing-address'), 200),
        error: (xhr, status, errorThrown) => {
          var errorResponse = $.parseJSON( xhr.responseText );
          customerData.set('messages', {
            messages: [{
              type: 'error',
              text: errorResponse.message
            }]
          });
        }
      });
    }
  });
</script>