<?php

$_order = $this->getOrder();
$_address = $_order->getShippingAddress();

$shipment = Mage::getModel('sales/service_order', $_order);
$collivery = Mage::getModel('mds_collivery/carrier_collivery');

if (true) {
	try {
		if ( isset( $_POST['mds_confirm_shipping_info'] ) && $_POST['mds_confirm_shipping_info'] ) {
			$validation = stripslashes($_POST['validation']);
			$data=json_decode($validation, TRUE);
			$new_col = $collivery->register_shipping($data);
			//$order->update_status('completed', 'MDS Shipping registered successfully.');
			//update_post_meta( $order->id, '_mds_status', 1 );
			//update_post_meta( $order->id, 'mds_waybill', $new_col['results']['collivery_id'] );
			echo "Shipping registered successfully. Waybill Number: ". $new_col['results']['collivery_id'];
		} else {
		
		$cptypes = $collivery->get_cptypes();
		$cptype = $_address->getMds_cptype();
		
		$towns = $collivery->get_towns();
		$town = $collivery->get_code($towns, $_address->getRegion());
		
		$suburbs = $collivery->get_suburbs($town);
		$suburb = $collivery->get_code($suburbs, $_address->getCity());
		
		$my_info=$collivery->my_info();
		
		$street = $_address->getStreet();
		$address=array(
			'companyName'=>$_address->getCompany(),
			'CP_Type'=>$cptype,
			'TownBrief'=>$town,
			'mapID'=>$suburb,
			'building'=>$_address->getMds_building(),
			'streetnum'=>$street[0],
			'street'=>$street[1],
			);
		$contact=array(
			'fname'=>$_address->getName(),
			'cellNo'=>$_address->getTelephone(),
			'emailAddr'=>$_address->getEmail(),
			);
?>

<style>
	.green {
		color: green;
	}
	.red {
		color: red;
	}
</style>
<h1>Confirm Shipping Information</h1>
<div style="float:left; width: 50%">
	<h2>Client Information</h2>
	<table>
		<tr>
			<td>Name</td>
			<td><?php echo $contact['fname']; ?></td>
		</tr>
		<tr>
			<td>Number</td>
			<td><?php echo $contact['cellNo']; ?></td>
		</tr>
		<tr>
			<td>Email Address</td>
			<td><?php echo $contact['emailAddr']; ?></td>
		</tr>
		<tr>
			<td>Company Name</td>
			<td><?php echo $address['companyName']; ?></td>
		</tr>
		<tr>
			<td>Location Type</td>
			<td><?php echo @$cptypes[$address['CP_Type']]; ?></td>
		</tr>
		<tr>
			<td>Town</td>
			<td><?php echo $towns[$address['TownBrief']]; ?></td>
		</tr>
		<tr>
			<td>Suburb</td>
			<td><?php echo $suburbs[$address['mapID']]; ?></td>
		</tr>
		<tr>
			<td>Building Details</td>
			<td><?php echo $address['building']; ?></td>
		</tr>
		<tr>
			<td>Street Number</td>
			<td><?php echo $address['streetnum']; ?></td>
		</tr>
		<tr>
			<td>Street Name</td>
			<td><?php echo $address['street']; ?></td>
		</tr>
	</table>
	<?php
		if (!isset( $_POST['mds_confirm_shipping_info'])&&!isset( $_POST['mds_add_client'])){ ?>
			<form method="post">
				<input type="hidden" name="form_key" value="<? echo $this->getFormKey(); ?>" />
				<input type="submit" class="button tips" name="mds_add_client" value="<?php echo __('Confirm Address'); ?>" data-tip="<?php echo __('Add client to MDS database.'); ?>" />
			</form>
		<?php }
	?>
</div>
<div style="float:right;  width: 50%">
	<h2>My Information</h2>
	<table>
		<tr>
			<td>Name</td>
			<td><?php echo $my_info['results']['fname']; ?></td>
		</tr>
		<tr>
			<td>Number</td>
			<td><?php echo $my_info['results']['cellNo']; ?></td>
		</tr>
		<tr>
			<td>Email Address</td>
			<td><?php echo $my_info['results']['emailAddr']; ?></td>
		</tr>
		<tr>
			<td>Company Name</td>
			<td><?php echo $my_info['results']['companyName']; ?></td>
		</tr>
		<tr>
			<td>Location Type</td>
			<td><?php echo $cptypes[$my_info['results']['CP_Type']]; ?></td>
		</tr>
		<tr>
			<td>Town</td>
			<td><?php echo $my_info['results']['TownName']; ?></td>
		</tr>
		<tr>
			<td>Suburb</td>
			<td><?php echo $my_info['results']['Suburb']; ?></td>
		</tr>
		<tr>
			<td>Building Details</td>
			<td><?php echo $my_info['results']['Address1']; ?></td>
		</tr>
		<tr>
			<td>Street Number</td>
			<td><?php echo $my_info['results']['Address3']; ?></td>
		</tr>
		<tr>
			<td>Street Name</td>
			<td><?php echo $my_info['results']['Address2']; ?></td>
		</tr>
	</table>
</div>
<?php
if ( isset( $_POST['mds_add_client'] ) && $_POST['mds_add_client'] ) {
	$client_address_id = $_address->getMds_address_id();
	$client_address_hash = $_address->getMds_address_hash();
	if (isset($client_address_id)&&$client_address_hash==md5(implode(',', $address)))
	{
		$cpid['results']=$client_address_id;
		echo "<p class=\"green\"><strong>Address already added, using previous ID</strong></p>";
	} else {
		$cpid = $collivery->addAddress($address);
	}
	
	$contact['cpid'] = $cpid['results'];
	
	if(isset($cpid['error_message'])) {
		print("Error - ".$cpid['error_message']);
		die();
	} else {
		$_address->setMds_address_id($cpid['results']);
		$_address->setMds_address_hash(md5(implode(',', $address)));
		$_address->save();
		
		$client_contact_id = $_address->getMds_contact_id();
		$client_contact_hash = $_address->getMds_contact_hash();
		if (isset($client_contact_id)&&$client_contact_hash==md5(implode(',', $contact)))
		{
			$ctid['results'] = $client_contact_id;
			echo "<p class=\"green\"><strong>Contact already added, using previous ID</strong></p>";
		} else {
			$ctid = $collivery->addContact($contact);
		}
		if(isset($ctid['error_message']))
			print("Error - ".$ctid['error_message']);
		else{
			$_address->setMds_contact_id($ctid['results']);
			$_address->setMds_contact_hash(md5(implode(',', $contact)));
			$_address->save();
			print("</strong></p><p class=\"green\"><strong>Address and Contact added succesfully!</strong></p>");
			
			$collivery_data = $collivery->get_cart_content($_order->getAllItems());
			$collivery_data['collivery_from']=$my_info['address_id'];
			$collivery_data['contact_from']=$my_info['contact_id'];
			$collivery_data['collivery_to']=$cpid['results'];
			$collivery_data['contact_to']=$ctid['results'];
			$collivery_data['collivery_type']=2;
			$collivery_data['service']=5;
			$collivery_data['mds_cover']=true;
			//print_r($collivery_data);
			$mds_contact = $collivery->get_client_contact($cpid['results']);
			$mds_address = $collivery->get_client_address($cpid['results']);
			
			$validation = $collivery->validate($collivery_data);
			?>
			<h2>Validated Information</h2>
			<table>
				<tr>
					<th>Description</th>
					<th>Data</th>
				</tr>
				<tr>
					<td>From (Address)</td>
					<td style="text-align: right;"><?php echo $validation['results']['collivery_from']; ?></td>
				</tr>
				<tr>
					<td>From (Contact)</td>
					<td style="text-align: right;"><?php echo $validation['results']['contact_from']; ?></td>
				</tr>
				<tr>
					<td>To (Address)</td>
					<td style="text-align: right;"><?php echo $validation['results']['collivery_to']; ?></td>
				</tr>
				<tr>
					<td>To (Contact)</td>
					<td style="text-align: right;"><?php echo $validation['results']['contact_to']; ?></td>
				</tr>
				<tr>
					<td>Collivery Type</td>
					<td style="text-align: right;"><?php echo $validation['results']['collivery_type']; ?></td>
				</tr>
				<tr>
					<td>Number of Packages</td>
					<td style="text-align: right;"><?php echo @$validation['results']['num_package']; ?></td>
				</tr>
				<tr>
					<td>Weight</td>
					<td style="text-align: right;"><?php echo $validation['results']['weight']; ?> Kg</td>
				</tr>
				<tr>
					<td>Volumetric Weight</td>
					<td style="text-align: right;"><?php echo @$validation['results']['vol_weight']; ?> Kg</td>
				</tr>
				<tr>
					<td>Service</td>
					<td style="text-align: right;"><?php echo $validation['results']['service']; ?></td>
				</tr>
				<tr>
					<td>MDS Cover</td>
					<td style="text-align: right;"><?php echo ($validation['results']['mds_cover']==1) ? "Yes" : "No"; ?></td>
				</tr>
				<tr>
					<td>Collection Time</td>
					<td style="text-align: right;"><?php echo date("H\:i \- D\, d F Y",$validation['results']['collection_time']); ?></td>
				</tr>
				<tr>
					<td>Delivery Time</td>
					<td style="text-align: right;"><?php echo date("H\:i \- D\, d F Y",$validation['results']['delivery_time']); ?></td>
				</tr>
			</table>
			<p>Client Charged: <strong>R<?php //echo $order->order_shipping; ?></strong><br>Actual Price: <strong>R<?php echo $validation['pricing']['results']['Total']; ?></strong></p>
			<form method="post">
				<input type="hidden" name="form_key" value="<? echo $this->getFormKey(); ?>" />
				<input type="hidden" name="validation" value="<?php echo htmlentities(json_encode($validation['results'])); ?>">
				<input type="submit" class="button tips" name="mds_confirm_shipping_info" value="<?php echo __('Accept Collivery'); ?>" data-tip="<?php echo __('Accept the Collivery and send someone to pickup shipping.'); ?>" />
			</form>
			<?php
					}
				}
			}
		}
	} catch (Exception $e) {
		throw $e;
	}
} else echo "<h1 class=\"red\">Error. Shipping has already been registered with MDS.</h1>
			<p>The shipping has already been placed with MDS Collivery. You can track the shipping with the following waybill: ";