<?php
$mds_waybill = $this->address->getMds_waybill();
if (!isset($mds_waybill)) {
	try {
		if ( isset( $_POST['validation'] ) && !(isset( $_POST['override_num_packages']) && $_POST['override_num_packages'] )) {
			$validation = stripslashes($_POST['validation']);
			$data=json_decode($validation, TRUE);
			$new_col = $this->collivery->register_shipping($data);
			$waybill = $new_col['results']['collivery_id'];
			
			$this->address->setMds_waybill($waybill);
			$this->address->save();
			
			$this->completeShipment($waybill);
			echo "Shipping registered successfully. Waybill Number: ". $waybill;
		} else {
			$address = $this->getAddress();
			$contact = $this->getContact();
			
			$cptypes = $this->collivery->get_cptypes();
			$towns = $this->collivery->get_towns();
			$town = $this->collivery->get_code($towns, $this->address->getRegion());
			$suburbs = $this->collivery->get_suburbs($town);
			$my_info=$this->collivery->my_info();
			
			if ( isset( $_POST['mds_add_client'] ) && $_POST['mds_add_client'] ) {
				$client_info = $this->addClient($address, $contact);
				$validation = $this->validate($client_info, $my_info);
			}
			
			if(isset($_POST['override_num_packages']) && $_POST['override_num_packages']){
				$raw_data = stripslashes($_POST['validation']);
				$data=json_decode($raw_data, TRUE);
				unset($data['num_package']);
				foreach ( $data['parcels'] as $key => $value ){
					unset($data['parcels'][$key]['qty']);
				}
				$validation = $this->collivery->validate($data);
			}
			?>
			<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>mds/modalbox.js" type="text/javascript"></script>
			<style>
				.green {
					color: green;
				}
				.red {
					color: red;
				}
				
				.button:disabled{
					background: #555555;
				}
				
				.modalbox {
					color: #333;
					display: none;
					position: absolute;
					top: 25%;
					left: 25%;
					width: 50%;
					height: 50%;
					padding: 1em;
					border: 1px solid #FFAC47;
					background-color: white;
					text-align: left;
					z-index:1001;
					overflow: auto;
				}
				
				#overlay{
					display:none;
					position:absolute;
					top:0;
					left:0;
					width:100%;
					height:100%;
					z-index:1000;
					background-color:#333;
					-moz-opacity: 0.8;
					opacity:.80;
					filter: alpha(opacity=80);
				}
				
				.modalbox[id]{ /* IE6 and below Can't See This */    position:fixed;    }#overlay[id]{ /* IE6 and below Can't See This */    position:fixed;    }
			</style>
			<h1>Confirm Shipping Information</h1>
			<div style="float:left; width: 50%">
				<h2>Client Information</h2>
				<table>
					<tr>
						<td>Name</td>
						<td><?php echo $contact['fname']; ?></td>
					</tr>
					<tr>
						<td>Number</td>
						<td><?php echo $contact['cellNo']; ?></td>
					</tr>
					<tr>
						<td>Email Address</td>
						<td><?php echo $contact['emailAddr']; ?></td>
					</tr>
					<tr>
						<td>Company Name</td>
						<td><?php echo $address['company_name']; ?></td>
					</tr>
					<tr>
						<td>Location Type</td>
						<td><?php echo @$cptypes[$address['address_type']]; ?></td>
					</tr>
					<tr>
						<td>Town</td>
						<td><?php echo $towns[$address['town_id']]; ?></td>
					</tr>
					<tr>
						<td>Suburb</td>
						<td><?php echo $suburbs[$address['suburb_id']]; ?></td>
					</tr>
					<tr>
						<td>Building Details</td>
						<td><?php echo $address['building']; ?></td>
					</tr>
					<tr>
						<td>Street Address</td>
						<td><?php echo $address['street']; ?></td>
					</tr>
				</table>
				<?php
					if (!isset( $validation )&&!isset( $_POST['mds_add_client'] )){ ?>
						<form method="post">
							<input type="hidden" name="form_key" value="<? echo $this->getFormKey(); ?>" />
							<input type="submit" class="button tips" name="mds_add_client" value="<?php echo __('Confirm Address'); ?>" data-tip="<?php echo __('Add client to MDS database.'); ?>" />
						</form>
					<?php }
				?>
			</div>
			<div style="float:right;  width: 50%">
				<h2>My Information</h2>
				<table>
					<tr>
						<td>Name</td>
						<td><?php echo $my_info['results']['fname']; ?></td>
					</tr>
					<tr>
						<td>Number</td>
						<td><?php echo $my_info['results']['cellNo']; ?></td>
					</tr>
					<tr>
						<td>Email Address</td>
						<td><?php echo $my_info['results']['emailAddr']; ?></td>
					</tr>
					<tr>
						<td>Company Name</td>
						<td><?php echo $my_info['results']['companyName']; ?></td>
					</tr>
					<tr>
						<td>Location Type</td>
						<td><?php echo $cptypes[$my_info['results']['CP_Type']]; ?></td>
					</tr>
					<tr>
						<td>Town</td>
						<td><?php echo $my_info['results']['TownName']; ?></td>
					</tr>
					<tr>
						<td>Suburb</td>
						<td><?php echo $my_info['results']['Suburb']; ?></td>
					</tr>
					<tr>
						<td>Building Details</td>
						<td><?php echo $my_info['results']['Address1']; ?></td>
					</tr>
					<tr>
						<td>Street Number</td>
						<td><?php echo $my_info['results']['Address3']; ?></td>
					</tr>
					<tr>
						<td>Street Name</td>
						<td><?php echo $my_info['results']['Address2']; ?></td>
					</tr>
				</table>
			</div>
			<?php 
			
			if (isset($client_info['message']))
				foreach ($client_info['message'] as $message) {
					echo $message;
				}
			
			if(isset($validation)): ?>
				<h2>Validated Information</h2>
				<table>
					<tr>
						<th>Description</th>
						<th>Data</th>
					</tr>
					<tr>
						<td>From (Address)</td>
						<td style="text-align: right;"><?php echo $validation['results']['collivery_from']; ?></td>
					</tr>
					<tr>
						<td>From (Contact)</td>
						<td style="text-align: right;"><?php echo $validation['results']['contact_from']; ?></td>
					</tr>
					<tr>
						<td>To (Address)</td>
						<td style="text-align: right;"><?php echo $validation['results']['collivery_to']; ?></td>
					</tr>
					<tr>
						<td>To (Contact)</td>
						<td style="text-align: right;"><?php echo $validation['results']['contact_to']; ?></td>
					</tr>
					<tr>
						<td>Number of Packages</td>
						<td style="text-align: right;"><?php echo @$validation['results']['num_package']; ?></td>
					</tr>
					<tr>
						<td>Weight</td>
						<td style="text-align: right;"><?php echo $validation['results']['weight']; ?> Kg</td>
					</tr>
					<tr>
						<td>Volumetric Weight</td>
						<td style="text-align: right;"><?php echo @$validation['results']['vol_weight']; ?> Kg</td>
					</tr>
					<tr>
						<td>Service</td>
						<td style="text-align: right;"><?php echo $validation['results']['service']; ?></td>
					</tr>
					<tr>
						<td>MDS Cover</td>
						<td style="text-align: right;"><?php echo (isset($validation['results']['mdscover'])&&$validation['results']['mdscover']==1) ? "Yes" : "No"; ?></td>
					</tr>
					<tr>
						<td>Collection Time</td>
						<td style="text-align: right;"><?php echo date("H\:i \- D\, d F Y",$validation['results']['collection_time']); ?></td>
					</tr>
					<tr>
						<td>Delivery Time</td>
						<td style="text-align: right;"><?php echo date("H\:i \- D\, d F Y",$validation['results']['delivery_time']); ?></td>
					</tr>
				</table>
				<p><!-- Client Charged: <strong>R<?php //echo $order->order_shipping; ?></strong><br>Actual --></br>Price: <strong>R<?php echo $validation['pricing']['results']['Total']; ?></strong></p>
				<?php
				if($validation['results']['REJECTED']){
					$reason = $validation['results']['REJECTED_REASON'];
					echo "<p class=\"red\"><strong>$reason</strong></p>";
				}else{ ?>
					<form method="post" id="validateForm">
						<input type="hidden" name="form_key" value="<? echo $this->getFormKey(); ?>" />
						<input type="hidden" name="validation" id="hiddenValidation" value="<?php echo htmlentities(json_encode($validation['results'])); ?>">
						<label for="override_num_packages">Override Number of Packages</label>
						<input type="checkbox" name="override_num_packages" id="override_num_packages">
					</form>
					<br>
					<button onclick="CheckForm();" class="button" name="mds_confirm_shipping_info"><?php echo __('Accept Collivery'); ?></button>
					<div id="modalbox" class="modalbox">
						<h1>Product Information</h1>
						<table style="width: 99%" id="parcels">
							<tr>
								<th>Length (cm)</th>
								<th>Width (cm)</th>
								<th>Height (cm)</th>
								<th>Weight (Kg)</th>
								<th>Qty</th>
								<th></th>
							</tr>
							<tr>
								<td><input type="text" id="length" name="length" style="width: 90%"></td>
								<td><input type="text" id="width" name="width" style="width: 90%"></td>
								<td><input type="text" id="height" name="height" style="width: 90%"></td>
								<td><input type="text" id="weight" name="weight" style="width: 90%"></td>
								<td><input type="text" id="qty" name="qty" style="width: 90%"></td>
								<td><button onclick="addParcel();" class="button">Add</button></td>
							</tr>
							<tr>
								<td></td>
								<td></td>
								<td>Total:</td>
								<td id="total_weight">0 Kg</td>
								<td id="total_qty">0</td>
								<td></td>
							</tr>
						</table>
						<p>
							<button onclick="modalClose();" class="button">Close</button>
							<button onclick="reValidate();" class="button" id="reValidateBtn">Re-Validate</button>
						</p>
					</div>
					<script>
						var validation = <?php echo json_encode($validation['results']); ?>;
					</script>
					<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>mds/admin.js" type="text/javascript"></script>
				<?php
				}
			endif;
		}
	} catch (Exception $e) {
		throw $e;
	}
} else {
	$status = $this->collivery->get_status($mds_waybill);
	$status_text = $status['results']['status_text'];
	$status_del_date = $status['results']['DelDate'];
	$status_del_time = $status['results']['DelTime'];
	echo "
		<h1 class=\"red\">Shipping has already been registered with MDS.</h1>
		<p>
			<table>
				<tr>
					<td>Waybill:</td>
					<td>$mds_waybill</td>
				</tr>
				<tr>
					<td>Status:</td>
					<td>$status_text</td>
				</tr>
				<tr>
					<td>Delivery Date:</td>
					<td>$status_del_date</td>
				</tr>
				<tr>
					<td>Delivery Time:</td>
					<td>$status_del_time</td>
				</tr>
			</table>
		</p>";
}
?>