<div class="col-set order-info-box">
    <div class="col">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('MDS Collivery') ?></h2>
            </div>
            <div class="box-content">
                
                	<?php
                		$values = $this->getMdsVars();
                		foreach($values as $key => $value){
                	?>
                		<b><?php echo $this->__($key);?></b> : <?php echo $value;?> <br/>
                	<?php } ?>
                
            </div>
        </div>
    </div>
</div>