<?php /** @var \MDS\Collivery\Block\Customer\Widget\CustomAddressEditWidget $block */ ?>
<div class="field custom">
  <label class="label" for="<?php echo $block->escapeHtml($block->getFieldId('location')) ?>">
    <span><?php echo $block->escapeHtml($block->getFieldLabel('location')) ?></span>
  </label>
  <div class="control">
    <select name="<?php echo $block->escapeHtml($block->getFieldName('location'));?>"
            required=""
            id="<?php echo $block->escapeHtml($block->getFieldId('location'));?>">
        <?php /* @escapeNotVerified  */ echo $block->getFieldParams()?>
      <option disabled="" selected="">Select location type</option>
      <?php
      $locations = (new MDS\Collivery\Model\Customer\Address\Attribute\Source\Location())->getAllOptions(true, false);
      foreach ($locations as $location) {
          $selected =  $location['value'] == $block->escapeHtml($block->getValue('location')) ? 'selected="selected"' : '';
          echo '<option value="' . $location['value'] . '" ' . $selected . '>' . $location['label'] . '</option>';
      }
      ?>
    </select>
  </div>
</div>
<div class="field custom">
  <label class="label" for="<?php echo $block->escapeHtml($block->getFieldId('town')) ?>">
    <span><?php echo $block->escapeHtml($block->getFieldLabel('Town')) ?></span>
  </label>
  <div class="control">
    <select name="<?php echo $block->escapeHtml($block->getFieldName('town'));?>"
            required=""
            id="<?php echo $block->escapeHtml($block->getFieldId('town'));?>">
        <?php /* @escapeNotVerified  */ echo $block->getFieldParams()?>
      <option disabled="" selected="">Select Town</option>
        <?php
        $towns = (new MDS\Collivery\Model\Customer\Address\Attribute\Source\Town())->getAllOptions(true, false);
        foreach ($towns as $town) {
            $selected =  $town['value'] == $block->escapeHtml($block->getValue('town')) ? 'selected="selected"' : '';
            echo '<option value="' . $town['value'] . '" ' . $selected . ' >' . $town['label'] . '</option>';
        }
        ?>
    </select>
  </div>
</div>
<div class="field custom">
  <label class="label" for="<?php echo $block->escapeHtml($block->getFieldId('suburb')) ?>">
    <span><?php echo $block->escapeHtml($block->getFieldLabel('Suburb')) ?></span>
  </label>
  <div class="control">
    <select name="<?php echo $block->escapeHtml($block->getFieldName('suburb'));?>"
            required=""
            id="<?php echo $block->escapeHtml($block->getFieldId('suburb'));?>">
        <?php /* @escapeNotVerified  */ echo $block->getFieldParams()?>
        <?php
        $suburbs = (new MDS\Collivery\Model\Customer\Address\Attribute\Source\Suburb($block->escapeHtml($block->getValue('town'))))
            ->getAllOptions(true, false);
        if ($suburbs) {
            foreach ($suburbs as $suburb) {
                $selected =  $suburb['value'] == $block->escapeHtml($block->getValue('suburb')) ? 'selected="selected"' : '';
                echo '<option value="' . $suburb['value'] . '" ' . $selected . '>' . $suburb['label'] . '</option>';
            }
        }

        ?>
    </select>
  </div>
</div>

<script type="text/javascript">
  require(['jquery','mage/url','domReady!'], function ($) {
    $(document).find('div.field.city, #street_2, #street_3').hide();
    var suburb = $('select[name="suburb"]');
    $('select[name="town"]').change(function () {
      var city = $('select[name="town"] option:selected').text();
      $(document).find('input[name="city"]').val(city).trigger('focus').trigger('keyup');
      window.getSuburbs($('form[class="form-address-edit"] select[name="suburb"]') ,$(this).val());
      suburb.trigger('change');
    });
    suburb.change(function () {
      $('#street_2').attr('value', $('option:selected',this).text())
    });
  });
</script>
